// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxzgqwglwifwzomfobmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4emdxd2dsd2lmd3pvbWZvYm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTQ1ODIsImV4cCI6MjA2NzE3MDU4Mn0.M8Wt0-cOzn6oF_TZd63iadluE56DUh2uKenzoV2UDLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});